menu_slugs: ''
home_title: ''
home_description: ''
guest_overlay_title: ''
guest_overlay_list:
  type: list
  default: ""
  description:
    en: A list of text items that appears on the guest overlay
login_link: 'https://pianogroove.memberful.com/auth/sign_in'
sign_up_link: 'https://www.pianogroove.com/join/?utm_source=forum&utm_medium=button&utm_content=overlay'
